import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Physical NFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Buy my Physical NFTs
        </h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <Image src='/img/iphone2.png' alt='' width={150} height={200} />
            <p>New Iphone shope</p>
          </a>
          <a href="https://nextjs.org/docs" className={styles.card}>
          <Image src='/img/iphone3.png' alt='' width={150} height={200} />
            <p>Acessories for the iphone.</p>
          </a> 
      
        </div>
      </main>

    </div>
  )
}
